# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab6.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab6.proto\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\"\n\x03\x61\x64\x64\x12\x1b\n\x03\x61\x64\x64\x12\x07.addMsg\x1a\t.addReply\"\x00\x32>\n\ndotProduct\x12\x30\n\ndotProduct\x12\x0e.dotProductMsg\x1a\x10.dotProductReply\"\x00\x32-\n\x05image\x12$\n\x05image\x12\x0c.rawImageMsg\x1a\x0b.imageReply\"\x00\x32\x36\n\tjsonImage\x12)\n\tjsonImage\x12\r.jsonImageMsg\x1a\x0b.imageReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab6_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDMSG']._serialized_start=14
  _globals['_ADDMSG']._serialized_end=44
  _globals['_ADDREPLY']._serialized_start=46
  _globals['_ADDREPLY']._serialized_end=69
  _globals['_DOTPRODUCTMSG']._serialized_start=71
  _globals['_DOTPRODUCTMSG']._serialized_end=108
  _globals['_DOTPRODUCTREPLY']._serialized_start=110
  _globals['_DOTPRODUCTREPLY']._serialized_end=147
  _globals['_RAWIMAGEMSG']._serialized_start=149
  _globals['_RAWIMAGEMSG']._serialized_end=175
  _globals['_JSONIMAGEMSG']._serialized_start=177
  _globals['_JSONIMAGEMSG']._serialized_end=204
  _globals['_IMAGEREPLY']._serialized_start=206
  _globals['_IMAGEREPLY']._serialized_end=249
  _globals['_ADD']._serialized_start=251
  _globals['_ADD']._serialized_end=285
  _globals['_DOTPRODUCT']._serialized_start=287
  _globals['_DOTPRODUCT']._serialized_end=349
  _globals['_IMAGE']._serialized_start=351
  _globals['_IMAGE']._serialized_end=396
  _globals['_JSONIMAGE']._serialized_start=398
  _globals['_JSONIMAGE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
